# Generated by Django 5.0.6 on 2024-07-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=64)),
                ('person_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=16)),
                ('code', models.CharField(max_length=64)),
                ('comision', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('accepted', models.BooleanField(default=False)),
                ('transfered', models.BooleanField(default=False)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
